# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevhelloworld',
                'doc_host': 'https://frankausberlin.github.io',
                'git_url': 'https://github.com/frankausberlin/nbdevhelloworld',
                'lib_path': 'nbdevhelloworld'},
  'syms': { 'nbdevhelloworld.core': { 'nbdevhelloworld.core.foo': ('core.html#foo', 'nbdevhelloworld/core.py'),
                                      'nbdevhelloworld.core.say_hello': ('core.html#say_hello', 'nbdevhelloworld/core.py')}}}
